# Generated by Django 6.0 on 2026-03-09 17:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('business', 'Business')], default='free', max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('annual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('features', models.JSONField(default=dict, help_text='Plan-specific features')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_type', models.CharField(choices=[('standard', 'Standard'), ('enterprise', 'Enterprise'), ('trial', 'Trial')], default='standard', max_length=20)),
                ('is_public', models.BooleanField(default=True, help_text='Show in public pricing page')),
                ('allow_self_service_changes', models.BooleanField(default=True, help_text='Allow users to change to/from this plan without approval')),
                ('minimum_commitment_days', models.IntegerField(default=0, help_text='Minimum days user must stay on this plan')),
            ],
            options={
                'db_table': 'subscription_plans',
                'ordering': ['sort_order', 'monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(help_text="2-letter ISO country code (e.g. 'IN', 'GB') or 'EU' / 'DEFAULT'.", max_length=10, unique=True)),
                ('tax_name', models.CharField(help_text="Display name for the tax (e.g. 'GST (18%)')", max_length=50)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Tax rate as a decimal (e.g. 0.18 for 18%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tax_rates',
                'ordering': ['country_code'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('subscription', 'Subscription'), ('token_purchase', 'Token Purchase'), ('upgrade', 'Plan Upgrade')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='INR', max_length=3)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('tokens_purchased', models.IntegerField(default=0, help_text='Tokens purchased in this transaction')),
                ('billing_address', models.JSONField(blank=True, default=dict)),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CeleryTaskRunner',
            fields=[
            ],
            options={
                'verbose_name': 'Celery Task Runner',
                'verbose_name_plural': '⚙️ Celery Task Runner (Payments)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.payment',),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('razorpay_payment_id', models.CharField(blank=True, help_text='Razorpay Payment ID', max_length=100, null=True, unique=True)),
                ('method_type', models.CharField(choices=[('card', 'Credit/Debit Card'), ('netbanking', 'Net Banking'), ('upi', 'UPI'), ('wallet', 'Wallet')], max_length=20)),
                ('last4', models.CharField(blank=True, help_text='Last 4 digits of card', max_length=4)),
                ('card_network', models.CharField(blank=True, help_text='Visa, Mastercard, etc.', max_length=50)),
                ('card_issuer', models.CharField(blank=True, help_text='Bank name', max_length=100)),
                ('card_type', models.CharField(blank=True, help_text='credit/debit', max_length=20)),
                ('upi_vpa', models.CharField(blank=True, help_text='UPI VPA', max_length=100)),
                ('bank_name', models.CharField(blank=True, help_text='Bank name for netbanking', max_length=100)),
                ('wallet_name', models.CharField(blank=True, help_text='Wallet provider name', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_methods',
                'ordering': ['-is_default', '-last_used_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('referrer_bonus_tokens', models.IntegerField(default=5000)),
                ('referee_bonus_tokens', models.IntegerField(default=2000)),
                ('total_referrals', models.IntegerField(default=0)),
                ('total_earned_tokens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'referral_codes',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('referrer_tokens_awarded', models.IntegerField(default=0)),
                ('referee_tokens_awarded', models.IntegerField(default=0)),
                ('rewards_processed', models.BooleanField(default=False)),
                ('referee_subscribed', models.BooleanField(default=False)),
                ('subscription_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.referralcode')),
            ],
            options={
                'db_table': 'referrals',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('trial', 'Trial')], default='trial', max_length=20)),
                ('daily_reset_date', models.DateField(default=django.utils.timezone.now)),
                ('monthly_reset_date', models.DateField(default=django.utils.timezone.now)),
                ('is_blocked', models.BooleanField(default=False)),
                ('block_reason', models.TextField(blank=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('usage_warning_sent', models.BooleanField(default=False)),
                ('usage_critical_sent', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_period_end', models.DateTimeField()),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('razorpay_subscription_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('razorpay_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('is_trial', models.BooleanField(default=False)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_billing_cycle', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('annual', 'Annual')], help_text='Billing cycle for scheduled plan', max_length=20, null=True)),
                ('scheduled_change_reason', models.CharField(blank=True, help_text='Reason for scheduled change (downgrade/upgrade)', max_length=255)),
                ('last_payment_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='success', max_length=20)),
                ('failed_payment_count', models.IntegerField(default=0, help_text='Number of consecutive failed payments')),
                ('plan_source', models.CharField(choices=[('standard', 'Standard'), ('promo', 'Promotional'), ('coupon', 'Coupon'), ('enterprise', 'Enterprise'), ('referral', 'Referral')], default='standard', max_length=50)),
                ('promo_code_used', models.CharField(blank=True, max_length=50)),
                ('commitment_end_date', models.DateTimeField(blank=True, help_text='Minimum commitment period for special plans', null=True)),
                ('requires_admin_approval', models.BooleanField(default=False, help_text='Requires admin approval for plan changes')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.subscriptionplan')),
                ('scheduled_plan', models.ForeignKey(blank=True, help_text='Plan to switch to at next renewal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_subscriptions', to='payments.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_subscriptions',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.usersubscription'),
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_type', models.CharField(choices=[('payment_receipt', 'Payment Receipt'), ('payment_failure', 'Payment Failure'), ('subscription_reminder', 'Subscription Reminder'), ('refund_notification', 'Refund Notification'), ('trial_expiring', 'Trial Expiring Soon'), ('trial_expired', 'Trial Expired'), ('subscription_expired', 'Subscription Expired'), ('subscription_suspended', 'Subscription Suspended'), ('subscription_renewed', 'Subscription Renewed'), ('plan_change_applied', 'Plan Change Applied'), ('low_token_balance', 'Low Token Balance')], max_length=50)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('failed_final', 'Failed Final'), ('bounced', 'Bounced'), ('opened', 'Opened'), ('clicked', 'Clicked')], default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='payments.payment')),
            ],
            options={
                'db_table': 'email_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='email_logs_user_id_fdc1a8_idx'), models.Index(fields=['email_type', '-created_at'], name='email_logs_email_t_6d62ae_idx'), models.Index(fields=['status', '-created_at'], name='email_logs_status_012124_idx'), models.Index(fields=['created_at'], name='email_logs_created_76afc3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'status'], name='user_subscr_user_id_c57286_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['razorpay_subscription_id'], name='user_subscr_razorpa_0865af_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['next_billing_date'], name='user_subscr_next_bi_c77a74_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', '-created_at'], name='payments_user_id_2c5fd7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['razorpay_order_id'], name='payments_razorpa_c67522_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['razorpay_payment_id'], name='payments_razorpa_c6ca42_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='payments_status_db6b16_idx'),
        ),
    ]
