# Generated by Django 6.0 on 2026-01-06 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='automation',
            name='automations_instagr_8b7a7d_idx',
        ),
        migrations.RemoveIndex(
            model_name='automation',
            name='automations_trigger_58146f_idx',
        ),
        migrations.RemoveIndex(
            model_name='automationtrigger',
            name='automation__automat_a0eab4_idx',
        ),
        migrations.RemoveIndex(
            model_name='automationtrigger',
            name='automation__status_51cbdb_idx',
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='contacts_instagr_fc73a2_idx',
        ),
        migrations.RemoveField(
            model_name='automationtrigger',
            name='automation',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='instagram_account',
        ),
        migrations.DeleteModel(
            name='Automation',
        ),
        migrations.DeleteModel(
            name='AutomationTrigger',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
