# Generated by Django 6.0 on 2026-01-08 11:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('analytics', '0002_remove_automation_automations_instagr_8b7a7d_idx_and_more'),
        ('automations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('provider', models.CharField(default='openrouter', max_length=50)),
                ('model_used', models.CharField(max_length=100)),
                ('total_requests', models.IntegerField(default=0)),
                ('successful_requests', models.IntegerField(default=0)),
                ('failed_requests', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0.0, help_text='Average AI response time (seconds)')),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=4, default=0.0, help_text='Estimated cost in USD', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_provider_metrics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='ai_provider_user_id_bf6b65_idx'), models.Index(fields=['model_used'], name='ai_provider_model_u_43e5aa_idx'), models.Index(fields=['date'], name='ai_provider_date_ad358f_idx')],
                'unique_together': {('user', 'date', 'model_used')},
            },
        ),
        migrations.CreateModel(
            name='AutomationPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('triggers_count', models.IntegerField(default=0)),
                ('successful_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0.0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('ai_enhanced_count', models.IntegerField(default=0)),
                ('ai_enhancement_rate', models.FloatField(default=0.0)),
                ('click_count', models.IntegerField(default=0, help_text='Clicks on DM buttons')),
                ('click_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='automations.automation')),
            ],
            options={
                'db_table': 'automation_performance',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['automation', '-date'], name='automation__automat_b0e249_idx'), models.Index(fields=['date'], name='automation__date_e02aea_idx')],
                'unique_together': {('automation', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ContactEngagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('dms_received', models.IntegerField(default=0)),
                ('ai_enhanced_dms', models.IntegerField(default=0)),
                ('responses_count', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0.0, help_text='Hours to respond')),
                ('button_clicks', models.IntegerField(default=0)),
                ('link_clicks', models.IntegerField(default=0)),
                ('tags_added', models.JSONField(blank=True, default=list)),
                ('tags_removed', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to='automations.contact')),
            ],
            options={
                'db_table': 'contact_engagement',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['contact', '-date'], name='contact_eng_contact_1a8605_idx'), models.Index(fields=['date'], name='contact_eng_date_7a60f0_idx')],
                'unique_together': {('contact', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_automations', models.IntegerField(default=0)),
                ('active_automations', models.IntegerField(default=0)),
                ('total_triggers', models.IntegerField(default=0)),
                ('successful_triggers', models.IntegerField(default=0)),
                ('failed_triggers', models.IntegerField(default=0)),
                ('skipped_triggers', models.IntegerField(default=0)),
                ('total_dms_sent', models.IntegerField(default=0)),
                ('ai_enhanced_dms', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0.0, help_text='Average time to send DM (seconds)')),
                ('success_rate', models.FloatField(default=0.0, help_text='Percentage of successful DMs')),
                ('ai_enhancement_rate', models.FloatField(default=0.0, help_text='Percentage of AI-enhanced messages')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='daily_stats_user_id_daf80f_idx'), models.Index(fields=['date'], name='daily_stats_date_c5e813_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('automation_created', 'Automation Created'), ('automation_activated', 'Automation Activated'), ('automation_deactivated', 'Automation Deactivated'), ('automation_deleted', 'Automation Deleted'), ('instagram_connected', 'Instagram Account Connected'), ('instagram_disconnected', 'Instagram Account Disconnected'), ('rate_limit_hit', 'Rate Limit Hit'), ('ai_provider_error', 'AI Provider Error'), ('dm_send_error', 'DM Send Error'), ('user_upgraded', 'User Plan Upgraded'), ('user_downgraded', 'User Plan Downgraded')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('automation_id', models.UUIDField(blank=True, null=True)),
                ('instagram_account_id', models.UUIDField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='system_even_user_id_bc3093_idx'), models.Index(fields=['event_type', '-created_at'], name='system_even_event_t_6b7422_idx'), models.Index(fields=['severity', '-created_at'], name='system_even_severit_fddb16_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instagram_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='accounts.instagramaccount')),
            ],
            options={
                'db_table': 'webhook_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['instagram_account', '-created_at'], name='webhook_log_instagr_5beb5b_idx'), models.Index(fields=['event_type', '-created_at'], name='webhook_log_event_t_8ccb28_idx'), models.Index(fields=['processed', '-created_at'], name='webhook_log_process_9cb915_idx')],
            },
        ),
    ]
