# Generated by Django 6.0 on 2026-01-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Email notification preferences'),
        ),
    ]
