# Generated by Django 6.0 on 2026-02-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='usersession',
            name='refresh_jti',
            field=models.CharField(blank=True, help_text='JWT ID of the refresh token associated with this session', max_length=255, null=True),
        ),
    ]
