# Generated by Django 6.0 on 2026-02-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usersession_options_usersession_refresh_jti'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_step',
            field=models.PositiveSmallIntegerField(default=0, help_text='Current step in the onboarding flow (0 = not started)'),
        ),
    ]
