# Generated by Django 6.0 on 2026-02-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_onboarding_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='connection_method',
            field=models.CharField(choices=[('facebook_graph', 'Facebook Graph API (Legacy)'), ('instagram_platform', 'Instagram Platform API (Direct)')], default='facebook_graph', max_length=50),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='platform_id',
            field=models.CharField(blank=True, help_text='New Instagram Platform user ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instagramaccount',
            name='instagram_user_id',
            field=models.CharField(help_text='Graph API user ID', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='instagramaccount',
            name='page_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
