# Generated by Django 6.0 on 2026-03-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_instagramaccount_connection_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='project_id',
        ),
    ]
