# Generated by Django 6.0 on 2026-03-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_feedback_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='following_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='media_count',
            field=models.IntegerField(default=0),
        ),
    ]
