# Generated by Django 6.0 on 2026-03-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_instagram_following_media_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(blank=True, default='password', max_length=50, null=True),
        ),
    ]
