# Generated by Django 6.0 on 2026-03-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_login_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
