"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from decouple import config

from pathlib import Path
# os is still needed for os.path and os.makedirs elsewhere
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')



# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)


ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=lambda v: [s.strip() for s in v.split(',')])

# In DEBUG mode, allow all ngrok tunnels automatically (URL changes on every restart)
if DEBUG:
    ALLOWED_HOSTS += [
        '.ngrok-free.app',   # Free ngrok tunnels (wildcard subdomain)
        '.ngrok.io',         # Paid ngrok tunnels
        '.netlify.app',
        'socialdmme.netlify.app',
        'localhost',
        '127.0.0.1',
    ]





# Application definition

INSTALLED_APPS = [
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'accounts',
    'automations',
    'analytics',
    'payments',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.RateLimitMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
     'NAME': 'accounts.validators.ComplexPasswordValidator',  # Custom validator
    },
    {
        'NAME': 'accounts.validators.CommonPasswordValidator',  # Custom validator
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"  # optional for production

# # For development only, optional
# STATICFILES_DIRS = [
#     BASE_DIR / "static",
# ]



# For production with PostgreSQL:
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': config('DB_NAME', default='DmMe_db'),
#         'USER': config('DB_USER', default='postgres'),
#         'PASSWORD': config('DB_PASSWORD'),
#         'HOST': config('DB_HOST', default='localhost'),
#         'PORT': config('DB_PORT', default='5432'),
#         'CONN_MAX_AGE': 600,  # Connection pooling
#     }
# }



# Google OAuth Configuration
GOOGLE_OAUTH_CLIENT_ID = config('GOOGLE_OAUTH_CLIENT_ID', default='')
GOOGLE_OAUTH_CLIENT_SECRET = config('GOOGLE_OAUTH_CLIENT_SECRET', default='')


# Razorpay Configuration
RAZORPAY_KEY_ID = config('RAZORPAY_KEY_ID', default='')
RAZORPAY_KEY_SECRET = config('RAZORPAY_KEY_SECRET', default='')
RAZORPAY_WEBHOOK_SECRET = config('RAZORPAY_WEBHOOK_SECRET', default='')
if not RAZORPAY_KEY_ID or not RAZORPAY_KEY_SECRET:
    import warnings
    warnings.warn(
        "⚠️  RAZORPAY_KEY_ID or RAZORPAY_KEY_SECRET not set in .env. "
        "Payment features will not work.",
        stacklevel=1
    )


AUTH_USER_MODEL = 'accounts.User'



# Channels Configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [(config('REDIS_HOST', default='localhost'), 6379)],
            'capacity': 10000,  # Handle 10k concurrent connections
            'expiry': 60,
        },
    },
}






# Celery Configuration
# Use 127.0.0.1 explicitly (not 'localhost') - on Windows, 'localhost' resolves to ::1 (IPv6)
# but Redis only listens on 127.0.0.1 (IPv4), causing WinError 10061 in kombu transport
_redis_url = config('REDIS_URL', default='redis://localhost:6379/0').replace('redis://localhost', 'redis://127.0.0.1')
CELERY_BROKER_URL = _redis_url
CELERY_RESULT_BACKEND = _redis_url

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_ALWAYS_EAGER = False  # Set to False so tasks run in background worker
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 300  # 5 minutes max per task

# ── Priority Queues (paid users get faster processing) ──────────────────────
# Run separate Celery workers per queue:
#   celery -A core worker -Q paid_high -c 8    (paid/high priority)
#   celery -A core worker -Q free_default -c 4  (free tier)
#   celery -A core worker -Q system -c 2         (tokens, beat tasks)
from kombu import Queue, Exchange

_default_exchange = Exchange('default', type='direct')

CELERY_TASK_QUEUES = (
    # Paid users: DM sends + AI enhancements (fastest workers)
    Queue('paid_high', _default_exchange, routing_key='paid_high'),
    # Free users: DM sends + AI enhancements (standard workers)
    Queue('free_default', _default_exchange, routing_key='free_default'),
    # System tasks: token refresh, queue processing (lowest priority)
    Queue('system', _default_exchange, routing_key='system'),
)

CELERY_TASK_DEFAULT_QUEUE = 'free_default'
CELERY_TASK_DEFAULT_EXCHANGE = 'default'
CELERY_TASK_DEFAULT_ROUTING_KEY = 'free_default'



# Celery Beat Schedule (automated tasks)
CELERY_BEAT_SCHEDULE = {
    # Retry any 'pending' triggers every 30s — safety net if .delay() failed at webhook time
    'retry-pending-triggers': {
        'task': 'automations.tasks.retry_pending_triggers',
        'schedule': 30.0,
        'options': {'queue': 'system'},
    },

    # COMMENT POLLING DISABLED — we use webhooks instead.
    # Polling via Instagram Platform API always returns 0 comments in Dev mode
    # and is redundant when webhooks are configured. Enable only as a fallback
    # if webhooks stop working (e.g. ngrok is down).
    # 'check-comments-fallback': {
    #     'task': 'automations.tasks.check_comments_bulk_async',
    #     'schedule': 300.0,  # every 5 minutes — only if webhooks are unavailable
    #     'options': {'queue': 'system'},
    # },

    # Refresh Instagram Platform API tokens daily — tokens last 60 days, refresh when < 15 days left
    'refresh-instagram-tokens-daily': {
        'task': 'automations.tasks.refresh_instagram_tokens',
        'schedule': 86400.0,  # every 24 hours
        'options': {'queue': 'system'},
    },
}



# Redis for caching and rate limiting
# Try Redis first, fallback to in-memory cache if Redis is unavailable (local dev)
if DEBUG:
    try:
        import redis
        r = redis.Redis(host='127.0.0.1', port=6379, socket_connect_timeout=1)
        r.ping()
        # Redis is running — use it
        CACHES = {
            'default': {
                'BACKEND': 'django_redis.cache.RedisCache',
                'LOCATION': config('REDIS_URL', default='redis://localhost:6379/1'),
                'OPTIONS': {
                    'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                    'CONNECTION_POOL_KWARGS': {
                        'max_connections': 50,
                        'retry_on_timeout': True,
                    }
                },
                'TIMEOUT': 3600,
            }
        }
    except Exception:
        # Redis not available — use in-memory cache for local development
        CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
                'TIMEOUT': 3600,
            }
        }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': config('REDIS_URL', default='redis://localhost:6379/1'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 50,
                    'retry_on_timeout': True,
                }
            },
            'TIMEOUT': 3600,
        }
    }




# JWT Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,

    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour'
    }

}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,

}

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
    "https://socialdmme.netlify.app",
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

from corsheaders.defaults import default_headers
CORS_ALLOW_HEADERS = list(default_headers) + [
    "ngrok-skip-browser-warning",
]




# Claude AI Settings
ANTHROPIC_API_KEY = config('ANTHROPIC_API_KEY', default='')





# ============================================================================
# INSTAGRAM API CONFIGURATION
# ============================================================================

INSTAGRAM_API_VERSION = 'v25.0'
INSTAGRAM_GRAPH_API_URL = f'https://graph.facebook.com/{INSTAGRAM_API_VERSION}'
INSTAGRAM_MAX_DMS_PER_HOUR = 100  # Rate limit per account


# Instagram OAuth (Legacy Facebook Graph API)
FACEBOOK_APP_ID = config('FACEBOOK_APP_ID')
FACEBOOK_APP_SECRET = config('FACEBOOK_APP_SECRET')

# Instagram Platform API (New Direct Login)
INSTAGRAM_CLIENT_ID = config('INSTAGRAM_CLIENT_ID', default='')
INSTAGRAM_CLIENT_SECRET = config('INSTAGRAM_CLIENT_SECRET', default='')

FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')
BACKEND_URL = config('BACKEND_URL', default='http://localhost:8000')


# Instagram Webhook Settings
INSTAGRAM_WEBHOOK_VERIFY_TOKEN = config('INSTAGRAM_WEBHOOK_VERIFY_TOKEN', default='your_secret_verify_token_12345')


# AI Enhancement Settings
AI_ENHANCEMENT_TIMEOUT = 60  # seconds
AI_ENHANCEMENT_MAX_RETRIES = 3
AI_ENHANCEMENT_FALLBACK_TO_ORIGINAL = True  # Use original message if all models fail





# CSRF Settings
CSRF_COOKIE_SECURE = not DEBUG  # Only send CSRF cookie over HTTPS in production
CSRF_COOKIE_HTTPONLY = True  # Prevent JavaScript access to CSRF cookie
CSRF_COOKIE_SAMESITE = 'Lax'  # Prevent CSRF attacks
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:5173',
    'https://socialdmme.netlify.app',
    'https://yourdomain.com',  # Add your production domain
]









# ============================================================================
# OPENROUTER AI CONFIGURATION
# ============================================================================

# OpenRouter API (unified gateway for all AI models)
OPENROUTER_API_KEY = config('OPENROUTER_API_KEY', default='')  # Legacy single key
# Multi-key rotation: comma-separated list of OpenRouter API keys.
# The AI service will rotate between these keys (15 req/min each, rotate every 5 min).
# If only one key is available, add the same key once or set OPENROUTER_API_KEYS equal to OPENROUTER_API_KEY.
OPENROUTER_API_KEYS = config('OPENROUTER_API_KEYS', default=OPENROUTER_API_KEY)
OPENROUTER_API_URL = 'https://openrouter.ai/api/v1'
OPENROUTER_SITE_URL = config('SITE_URL', default='https://DmMe.co')

# Model fallback chain (in priority order)
# OpenRouter provides access to all these models through one API
OPENROUTER_MODELS = [
    {
        'id': 'anthropic/claude-3.5-sonnet',
        'name': 'Claude 3.5 Sonnet',
        'max_tokens': 400,
        'cost_per_1k_tokens': 0.003,  # $3 per million tokens
        'speed': 'fast',
        'use_case': 'Best quality, primary model'
    },
    {
        'id': 'anthropic/claude-3-haiku',
        'name': 'Claude 3 Haiku',
        'max_tokens': 400,
        'cost_per_1k_tokens': 0.00025,  # $0.25 per million tokens
        'speed': 'very_fast',
        'use_case': 'Fast & cheap fallback'
    },
    {
        'id': 'openai/gpt-4-turbo',
        'name': 'GPT-4 Turbo',
        'max_tokens': 400,
        'cost_per_1k_tokens': 0.01,  # $10 per million tokens
        'speed': 'fast',
        'use_case': 'OpenAI flagship model'
    },
    {
        'id': 'openai/gpt-3.5-turbo',
        'name': 'GPT-3.5 Turbo',
        'max_tokens': 400,
        'cost_per_1k_tokens': 0.0005,  # $0.50 per million tokens
        'speed': 'very_fast',
        'use_case': 'Fast & reliable fallback'
    },
    {
        'id': 'meta-llama/llama-3.1-70b-instruct',
        'name': 'Llama 3.1 70B',
        'max_tokens': 400,
        'cost_per_1k_tokens': 0.0005,
        'speed': 'fast',
        'use_case': 'Open source option'
    },
]












# ============================================================================
# LOGGING
# ============================================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': config('DJANGO_LOG_LEVEL', default='INFO'),
        },
        'automations': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

# ============================================================================
# SECURITY SETTINGS (for production)
# ============================================================================

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# ============================================================================
# DEFAULT PRIMARY KEY FIELD TYPE
# ============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================================================================
# EMAIL SETTINGS (add to core/settings.py)
# ============================================================================

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='DmMe <noreply@DmMe.co>')













SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_SSL_REDIRECT = not DEBUG  # Force HTTPS in production

# Session Security
SESSION_COOKIE_SECURE = not DEBUG  # Only send session cookie over HTTPS
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access
SESSION_COOKIE_SAMESITE = 'Lax'  # Prevent CSRF
SESSION_COOKIE_AGE = 86400  # 24 hours

# ============================================================================
# CORS SETTINGS (for Netlify Frontend)
# ============================================================================

CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='', cast=lambda v: [s.strip() for s in v.split(',') if s.strip()])

# If no environment variable is set, use these defaults (Netlify)
if not CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS = [
        "https://socialdmme.netlify.app",
        "http://localhost:3000", # Common frontend dev port
        "http://localhost:5173", # Vite dev port
    ]

CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = ["Content-Type", "X-CSRFToken"]
CSRF_TRUSTED_ORIGINS = [origin.replace("https://", "https://*.") for origin in CORS_ALLOWED_ORIGINS if origin.startswith("https://")]
# Also trust Netlify directly
CSRF_TRUSTED_ORIGINS += ["https://socialdmme.netlify.app"]





 
