# Generated by Django 6.0 on 2026-01-06 13:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('trigger_type', models.CharField(choices=[('comment', 'Comment on Post'), ('story_mention', 'Story Mention'), ('story_reply', 'Story Reply'), ('dm_keyword', 'DM Keyword')], max_length=50)),
                ('trigger_keywords', models.JSONField(blank=True, default=list)),
                ('trigger_match_type', models.CharField(choices=[('exact', 'Exact Match'), ('contains', 'Contains'), ('any', 'Any Comment')], default='exact', max_length=20)),
                ('target_posts', models.JSONField(blank=True, default=list)),
                ('dm_message', models.TextField()),
                ('dm_buttons', models.JSONField(blank=True, default=list)),
                ('require_follow', models.BooleanField(default=False)),
                ('follow_check_message', models.TextField(blank=True, default='Please follow us first to receive the link!')),
                ('use_ai_enhancement', models.BooleanField(default=False)),
                ('ai_context', models.TextField(blank=True, help_text='Context for AI to personalize responses')),
                ('max_triggers_per_user', models.IntegerField(default=1, help_text='How many times a user can trigger this')),
                ('cooldown_minutes', models.IntegerField(default=0, help_text='Minutes to wait before re-triggering')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority automations run first')),
                ('total_triggers', models.IntegerField(default=0)),
                ('total_dms_sent', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instagram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='accounts.instagramaccount')),
            ],
            options={
                'db_table': 'automations',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instagram_user_id', models.CharField(max_length=100)),
                ('instagram_username', models.CharField(blank=True, max_length=100)),
                ('post_id', models.CharField(blank=True, max_length=100)),
                ('comment_id', models.CharField(blank=True, max_length=100)),
                ('comment_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'DM Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('dm_sent_at', models.DateTimeField(blank=True, null=True)),
                ('dm_message_sent', models.TextField(blank=True)),
                ('was_ai_enhanced', models.BooleanField(default=False)),
                ('ai_modifications', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='automations.automation')),
            ],
            options={
                'db_table': 'automation_triggers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('dm_message', models.TextField()),
                ('dm_buttons', models.JSONField(blank=True, default=list)),
                ('traffic_percentage', models.IntegerField(default=50, help_text='0-100%')),
                ('is_active', models.BooleanField(default=True)),
                ('total_sends', models.IntegerField(default=0)),
                ('total_clicks', models.IntegerField(default=0)),
                ('total_conversions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='automations.automation')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instagram_user_id', models.CharField(max_length=100)),
                ('instagram_username', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('profile_picture_url', models.URLField(blank=True)),
                ('total_interactions', models.IntegerField(default=0)),
                ('total_dms_received', models.IntegerField(default=0)),
                ('first_interaction', models.DateTimeField(auto_now_add=True)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('is_follower', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('instagram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='accounts.instagramaccount')),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
        migrations.AddIndex(
            model_name='automation',
            index=models.Index(fields=['instagram_account', 'is_active'], name='automations_instagr_8b7a7d_idx'),
        ),
        migrations.AddIndex(
            model_name='automation',
            index=models.Index(fields=['trigger_type'], name='automations_trigger_58146f_idx'),
        ),
        migrations.AddIndex(
            model_name='automationtrigger',
            index=models.Index(fields=['automation', 'instagram_user_id'], name='automation__automat_a0eab4_idx'),
        ),
        migrations.AddIndex(
            model_name='automationtrigger',
            index=models.Index(fields=['status', 'created_at'], name='automation__status_51cbdb_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['instagram_account', 'last_interaction'], name='contacts_instagr_fc73a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('instagram_account', 'instagram_user_id')},
        ),
    ]
