# Generated by Django 6.0 on 2026-01-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='comment_reply_message',
            field=models.CharField(blank=True, default='✅ Sent! Check your DM', help_text='Public reply to the comment. Use {username} for personalization.', max_length=200),
        ),
        migrations.AddField(
            model_name='automation',
            name='enable_comment_reply',
            field=models.BooleanField(default=True, help_text='Reply to the comment publicly before sending DM'),
        ),
        migrations.AddField(
            model_name='automation',
            name='total_comment_replies',
            field=models.IntegerField(default=0, help_text='Number of public comment replies sent'),
        ),
        migrations.AddField(
            model_name='automationtrigger',
            name='comment_reply_sent',
            field=models.BooleanField(default=False, help_text='Whether public comment reply was sent'),
        ),
        migrations.AddField(
            model_name='automationtrigger',
            name='comment_reply_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the comment reply was sent', null=True),
        ),
        migrations.AddField(
            model_name='automationtrigger',
            name='comment_reply_text',
            field=models.CharField(blank=True, help_text='The actual reply text sent to the comment', max_length=200),
        ),
        migrations.AddField(
            model_name='automationvariant',
            name='comment_reply_message',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='automation',
            name='ai_context',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='automation',
            name='cooldown_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='automation',
            name='dm_message',
            field=models.TextField(help_text='Private message sent via DM (can include links)'),
        ),
        migrations.AlterField(
            model_name='automation',
            name='follow_check_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='automation',
            name='max_triggers_per_user',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='automation',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='automation',
            name='require_follow',
            field=models.BooleanField(default=False, help_text='If True, user must follow before receiving DM'),
        ),
        migrations.AlterField(
            model_name='automationvariant',
            name='traffic_percentage',
            field=models.IntegerField(default=50),
        ),
        migrations.AddIndex(
            model_name='automationtrigger',
            index=models.Index(fields=['comment_id'], name='automation__comment_0f6550_idx'),
        ),
        migrations.AlterModelTable(
            name='automationvariant',
            table='automation_variants',
        ),
    ]
