# Generated by Django 6.0 on 2026-01-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_automation_comment_reply_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtrigger',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='automationtrigger',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='automationtrigger',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('sent', 'DM Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
    ]
